name: CI

on:
  push:
    branches: [ master, 2.x ]

  pull_request:
    branches: [ master, 2.x ]

jobs:
  Job:
    name: Node.js
    uses: node-modules/github-actions/.github/workflows/node-test.yml@master
    with:
      os: 'ubuntu-latest'
      version: '14, 16, 18, 20'
